name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          # This action handles the heavy lifting of NDK/SDK setup
          workdir: .
          buildozer_version: master

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          # Buildozer puts the APK in the 'bin' directory
          path: bin/*.apk
